#!/bin/bash
#===============================================================================
#
#          FILE: INSTALL
# 
#         USAGE: ./INSTALL
# 
#   DESCRIPTION: install vm ha plugin.
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: nova-compute hostname must be global unique. if you want restart nova-compute service, ssh without password access.
#        AUTHOR: Kevin Zhang, zhang.jinnan@99cloud.net
#  ORGANIZATION: 99cloud
#       CREATED: 04/14/2014 8:13:05 CST
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error
cp -rf etc/init.d/vmha /etc/init.d/
cp -rf opt/vmha /opt/

cd /
chmod +x /etc/init.d/vmha
chmod +x /opt/vmha/bin/vmha.sh
chkconfig --add vmha
#systemctl enable vmha
